### ISSUE TITLE
How to get refined fluid？

### ISSUE THREAD

**Issue by forestbat** [aminesebastian/StaticPower#1]
I don't know how to recipe it。

**Comment by aminesebastian** [comment]
The refined fluid system is something still under development. The multi block parts currently don't have recipes so you'll have to spawn them in to mess around. The blocks are in game - The Refinery Controller, any number of mixers, reactors, vents, and fluid ports are what you're going to need. Pump in all three fluids and you'll start to create refined fluid.

Hope that helps.

- Amine
