### ISSUE TITLE
Grinder recipe registration issue

### ISSUE THREAD

**Issue by TheLMiffy1111** [aminesebastian/StaticPower#3]
https://github.com/Theking5301/StaticPower/blob/629f847a451cb51b4109667bc8ca544a9ad57ee5/src/main/java/theking530/staticpower/handlers/crafting/recipes/GrinderRecipes.java#L183-L189

**Comment by aminesebastian** [comment]
Wow, haha good catch - I'll fix that right up. Thank you.
