### ISSUE TITLE
[Suggestion] Crafttweaker support

### ISSUE THREAD

**Issue by Zer0Lyfe** [aminesebastian/StaticPower#4]
Could you make your mods machines support crafttweaker. This would allow much more customization to your mod. if you are busy ATM, I don't mind when it is done.

**Comment by aminesebastian** [comment]
I was considering this - glad to hear people are interested in seeing it :)
It's on the docket for one of the next few releases

**Comment by Zer0Lyfe** [comment]
Thank you King :D

**Comment by aminesebastian** [comment]
Fixed on latest 1.15.2 version, all recipes are exposed using the JSON system.
